agent:
  name: Pytesseract_OCR_Agent
  description: "Agent to read image from folder, perform pytesseract prediction and save the inference image in file."

templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: {}

- template_name: FolderImageDatasetCV2
  class_name: FolderImageDatasetCV2
  template_input: InputTemplate
  attributes:
    data_dir: /home/roberto/Desktop

- template_name: PytesseractOCR
  class_name: PytesseractOCR
  template_input: FolderImageDatasetCV2
  attributes:
    lang: spa

- template_name: LabelDrawer
  class_name: LabelDrawer
  template_input: PytesseractOCR
  attributes:
    overwrite: true
    draw_classification_label: true

- template_name: ImageSaver
  class_name: ImageSaver
  template_input: LabelDrawer
  attributes:
    save_dir: dataset
    root_dir: /home/roberto/PycharmProjects/sinapsis-ocr